[
  {
    "make": "Toyota",
    "model": "Camry",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Honda",
    "model": "CR-V",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "F-150",
    "size": "Fullsize",
    "type": "Truck",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 20,
    "range": 320,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Tahoe",
    "size": "Fullsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 18,
    "range": 300,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Altima",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Rav4",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Escape",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Silverado",
    "size": "Fullsize",
    "type": "Truck",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 17,
    "range": 290,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Honda",
    "model": "Pilot",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 350,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Volkswagen",
    "model": "Jetta",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Santa Fe",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 370,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Jeep",
    "model": "Cherokee",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Explorer",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 380,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Malibu",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 410,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Highlander",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 360,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Sentra",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 32,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Tesla",
    "model": "Model Y",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Electric",
    "mpg": null,
    "range": 300,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Mustang",
    "size": "Compact",
    "type": "Coupe",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 330,
    "passenger_capacity": 4,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Equinox",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Honda",
    "model": "Accord",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Jeep",
    "model": "Grand Cherokee",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 21,
    "range": 320,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Subaru",
    "model": "Legacy",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 390,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mazda",
    "model": "CX-9",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 350,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Edge",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 370,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Malibu",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 410,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Highlander",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 360,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Volkswagen",
    "model": "Tiguan",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Elantra",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 33,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Kia",
    "model": "Sorento",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 340,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Audi",
    "model": "Q5",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "BMW",
    "model": "3 Series",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mercedes-Benz",
    "model": "GLC",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 320,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volvo",
    "model": "XC90",
    "size": "Fullsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 22,
    "range": 300,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Lexus",
    "model": "RX",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 30,
    "range": 450,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Jaguar",
    "model": "F-PACE",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 370,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Tesla",
    "model": "Model 3",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Electric",
    "mpg": null,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Porsche",
    "model": "Cayenne",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Land Rover",
    "model": "Discovery",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 21,
    "range": 320,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Subaru",
    "model": "Outback",
    "size": "Midsize",
    "type": "Wagon",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Acura",
    "model": "MDX",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 340,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Buick",
    "model": "Enclave",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 21,
    "range": 320,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "GMC",
    "model": "Terrain",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Kia",
    "model": "Telluride",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 330,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Lexus",
    "model": "NX",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 31,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mazda",
    "model": "Mazda6",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Maverick",
    "size": "Compact",
    "type": "Truck",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 42,
    "range": 500,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Trailblazer",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Tucson",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Jeep",
    "model": "Renegade",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Rogue",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 370,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Subaru",
    "model": "Forester",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 33,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Prius",
    "size": "Compact",
    "type": "Hatchback",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 54,
    "range": 600,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volkswagen",
    "model": "Atlas",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 350,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Audi",
    "model": "A4",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "BMW",
    "model": "X5",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mercedes-Benz",
    "model": "GLE",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "size": "Fullsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 320,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Colorado",
    "size": "Compact",
    "type": "Truck",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Sienna",
    "size": "Minivan",
    "type": "Van",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 36,
    "range": 500,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Jeep",
    "model": "Wrangler",
    "size": "Compact",
    "type": "SUV",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 22,
    "range": 300,
    "passenger_capacity": 4,
    "transmission": "Manual"
  },
  {
    "make": "Subaru",
    "model": "Crosstrek",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 35,
    "range": 450,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Honda",
    "model": "Civic",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 32,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "GMC",
    "model": "Acadia",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 340,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Kia",
    "model": "Soul",
    "size": "Compact",
    "type": "Hatchback",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Armada",
    "size": "Fullsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 18,
    "range": 310,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Mazda",
    "model": "CX-5",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Ranger",
    "size": "Compact",
    "type": "Truck",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volkswagen",
    "model": "Passat",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Traverse",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 22,
    "range": 340,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Avalon",
    "size": "Fullsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 32,
    "range": 450,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Honda",
    "model": "Fit",
    "size": "Subcompact",
    "type": "Hatchback",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 36,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Palisade",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 360,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Maxima",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Jeep",
    "model": "Compass",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Fusion",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 31,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Kia",
    "model": "Forte",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 34,
    "range": 440,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Subaru",
    "model": "Ascent",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 330,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Mazda",
    "model": "MX-5 Miata",
    "size": "Compact",
    "type": "Convertible",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 300,
    "passenger_capacity": 2,
    "transmission": "Manual"
  },
  {
    "make": "Buick",
    "model": "Encore",
    "size": "Subcompact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Tacoma",
    "size": "Compact",
    "type": "Truck",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 20,
    "range": 320,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Venue",
    "size": "Subcompact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 32,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Audi",
    "model": "A3",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volvo",
    "model": "S60",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 32,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Titan",
    "size": "Fullsize",
    "type": "Truck",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 18,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Honda",
    "model": "HR-V",
    "size": "Subcompact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Equinox",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Escape",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 41,
    "range": 500,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Highlander",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 36,
    "range": 480,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Kia",
    "model": "Rio",
    "size": "Subcompact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 33,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Subaru",
    "model": "Legacy",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 35,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Ioniq",
    "size": "Compact",
    "type": "Hatchback",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 59,
    "range": 690,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mitsubishi",
    "model": "Outlander",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 26,
    "range": 330,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Chrysler",
    "model": "Pacifica",
    "size": "Minivan",
    "type": "Van",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 32,
    "range": 480,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Acura",
    "model": "RDX",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volvo",
    "model": "V60",
    "size": "Midsize",
    "type": "Wagon",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 32,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Jeep",
    "model": "Cherokee",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 31,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Buick",
    "model": "Regal",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Edge",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Malibu",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 32,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Santa Cruz",
    "size": "Compact",
    "type": "Truck",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "C-HR",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volkswagen",
    "model": "Touareg",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Kicks",
    "size": "Subcompact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 33,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mazda",
    "model": "CX-9",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 330,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Honda",
    "model": "Insight",
    "size": "Compact",
    "type": "Hybrid",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 52,
    "range": 600,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Subaru",
    "model": "BRZ",
    "size": "Compact",
    "type": "Coupe",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 350,
    "passenger_capacity": 4,
    "transmission": "Manual"
  },
  {
    "make": "Ford",
    "model": "Mustang",
    "size": "Compact",
    "type": "Coupe",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 320,
    "passenger_capacity": 4,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Blazer",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "4Runner",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 19,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Kia",
    "model": "Seltos",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 31,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "370Z",
    "size": "Compact",
    "type": "Coupe",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 300,
    "passenger_capacity": 2,
    "transmission": "Manual"
  },
  {
    "make": "Hyundai",
    "model": "Kona",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 30,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volvo",
    "model": "XC40",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 320,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mitsubishi",
    "model": "Eclipse Cross",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Audi",
    "model": "Q5",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mercedes-Benz",
    "model": "GLC",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Mach-E",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Electric",
    "mpg": null,
    "range": 300,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Camaro",
    "size": "Compact",
    "type": "Coupe",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 22,
    "range": 290,
    "passenger_capacity": 4,
    "transmission": "Automatic"
  },
  {
    "make": "Toyota",
    "model": "Land Cruiser",
    "size": "Fullsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 13,
    "range": 320,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Kia",
    "model": "Telluride",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 380,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Murano",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 20,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Santa Fe",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volvo",
    "model": "XC60",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mitsubishi",
    "model": "Mirage",
    "size": "Subcompact",
    "type": "Hatchback",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 39,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Jeep",
    "model": "Grand Cherokee",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Audi",
    "model": "A5",
    "size": "Compact",
    "type": "Coupe",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 350,
    "passenger_capacity": 4,
    "transmission": "Automatic"
  },
  {
    "make": "Tesla",
    "model": "Model 3",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Electric",
    "mpg": null,
    "range": 320,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Volkswagen",
    "model": "Atlas",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 20,
    "range": 340,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Bronco",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 20,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Kia",
    "model": "Stinger",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Rogue",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mazda",
    "model": "Mazda3",
    "size": "Compact",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 31,
    "range": 420,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Hyundai",
    "model": "Tucson",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Subaru",
    "model": "Outback",
    "size": "Midsize",
    "type": "Wagon",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 26,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "BMW",
    "model": "X5",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mercedes-Benz",
    "model": "GLE",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 19,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Tesla",
    "model": "Model Y",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Electric",
    "mpg": null,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Porsche",
    "model": "Cayenne",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 19,
    "range": 330,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Chevrolet",
    "model": "Trailblazer",
    "size": "Subcompact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 29,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Lexus",
    "model": "RX",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 30,
    "range": 450,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Ford",
    "model": "Expedition",
    "size": "Fullsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 22,
    "range": 400,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Infiniti",
    "model": "QX60",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 20,
    "range": 340,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Cadillac",
    "model": "XT5",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 24,
    "range": 360,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Acura",
    "model": "MDX",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 27,
    "range": 380,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Lexus",
    "model": "NX",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 31,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },{
    "make": "Toyota",
    "model": "Sienna",
    "size": "Minivan",
    "type": "Van",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 36,
    "range": 500,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Porsche",
    "model": "911",
    "size": "Compact",
    "type": "Coupe",
    "doors": 2,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 320,
    "passenger_capacity": 4,
    "transmission": "Automatic"
  },
  {
    "make": "GMC",
    "model": "Yukon",
    "size": "Fullsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 20,
    "range": 400,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Buick",
    "model": "Enclave",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 22,
    "range": 360,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Nissan",
    "model": "Armada",
    "size": "Fullsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 18,
    "range": 380,
    "passenger_capacity": 8,
    "transmission": "Automatic"
  },
  {
    "make": "Genesis",
    "model": "G80",
    "size": "Midsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 23,
    "range": 350,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Mazda",
    "model": "CX-30",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 28,
    "range": 380,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Lincoln",
    "model": "Corsair",
    "size": "Compact",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 25,
    "range": 340,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  },
  {
    "make": "Audi",
    "model": "Q7",
    "size": "Midsize",
    "type": "SUV",
    "doors": 4,
    "fuel_type": "Gasoline",
    "mpg": 21,
    "range": 380,
    "passenger_capacity": 7,
    "transmission": "Automatic"
  },
  {
    "make": "Lexus",
    "model": "LS",
    "size": "Fullsize",
    "type": "Sedan",
    "doors": 4,
    "fuel_type": "Hybrid",
    "mpg": 28,
    "range": 400,
    "passenger_capacity": 5,
    "transmission": "Automatic"
  }
]